### ISSUE TITLE
Publish newer versions to the Chef supermarket

### ISSUE THREAD

**Issue by martinisoft** [express42-cookbooks/postgresql#13]
Hi there. First, I want to thank you for making an excellent cookbook! It's a lot easier to use with the wrapper cookbook pattern than the popular postgres cookbook out there now.

Can you please publish versions newer than 1.0.0 to the Chef supermarket to make it easier for inclusion? Thanks! :heart:

**Comment by martinisoft** [comment]
As another note, I noticed there is only a 1.0.0 git tag and nothing newer for versioned releases. Could you create tags for these versions or perhaps tag version 1.1.7 onward? This will also make it easier to follow releases.

**Comment by sample** [comment]
Hi, thanks for using our cookbook! We're going to do automatic publishing to supermarket all of our @express42-cookbooks in next month. Version 1.1.7 will be published tomorrow.

**Comment by sample** [comment]
1.1.7 in supermarket now.
